project_id = "zzmwjidgejbacqcluwyh"

[functions.bold-checkout]
verify_jwt = false

[functions.bold-webhook]
verify_jwt = false

[functions.whatsapp-exchange-token]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send-message]
verify_jwt = false

[functions.convert-audio]
verify_jwt = false

[functions.messenger-webhook]
verify_jwt = false

[functions.messenger-send-message]
verify_jwt = false