// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-conversations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's most recent HeyHey conversations across all connected WhatsApp/messaging accounts. Returns id, customer name/phone, platform, unread count and last update.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum conversations to return (1-100)."),
    only_unread: z.boolean().default(false).describe("If true, only return conversations with unread inbound messages.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, only_unread }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("conversations").select("id, customer_name, customer_phone, platform, unread_count, last_message_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (only_unread) q = q.gt("unread_count", 0);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-messages.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_messages_default = defineTool2({
  name: "get_conversation_messages",
  title: "Get conversation messages",
  description: "Return the most recent messages in a HeyHey conversation the signed-in user has access to. Each message includes direction (inbound/outbound), text content, type and timestamp.",
  inputSchema: {
    conversation_id: z2.string().uuid().describe("HeyHey conversation UUID (from list_conversations)."),
    limit: z2.number().int().min(1).max(200).default(30).describe("Maximum messages to return (1-200, newest first).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("messages").select("id, direction, content, message_type, status, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ordered = (data ?? []).reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(ordered) }],
      structuredContent: { messages: ordered }
    };
  }
});

// src/lib/mcp/tools/send-whatsapp-message.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sbUser(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var send_whatsapp_message_default = defineTool3({
  name: "send_whatsapp_message",
  title: "Send WhatsApp message",
  description: "Send a plain text WhatsApp message inside an existing HeyHey conversation on behalf of the signed-in user. Meta's 24h service window applies for Cloud API accounts.",
  inputSchema: {
    conversation_id: z3.string().uuid().describe("HeyHey conversation UUID to reply to."),
    text: z3.string().min(1).describe("Message text to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async ({ conversation_id, text }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const client = sbUser(ctx);
    const { data: conv, error: convErr } = await client.from("conversations").select("id, whatsapp_account_id, platform").eq("id", conversation_id).maybeSingle();
    if (convErr || !conv) {
      return {
        content: [{ type: "text", text: convErr?.message ?? "Conversation not found or no access." }],
        isError: true
      };
    }
    const fnName = conv.platform === "whatsapp_external" ? "whatsapp-send-external" : "whatsapp-send-message";
    const { data, error } = await client.functions.invoke(fnName, {
      body: {
        conversationId: conversation_id,
        conversation_id,
        whatsappAccountId: conv.whatsapp_account_id,
        content: text,
        text,
        type: "text"
      }
    });
    if (error) {
      return { content: [{ type: "text", text: `Send failed: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Message sent." }],
      structuredContent: { ok: true, result: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gnnucexcnkuevxfepwmw";
var mcp_default = defineMcp({
  name: "heyhey-mcp",
  title: "HeyHey",
  version: "0.1.0",
  instructions: "Tools for HeyHey (heyhey.site) \u2014 a unified inbox for WhatsApp, Messenger, Instagram and TikTok. Each caller acts as their signed-in HeyHey user. Use `list_conversations` to browse recent chats, `get_conversation_messages` to read a thread, and `send_whatsapp_message` to reply on WhatsApp.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_conversations_default, get_messages_default, send_whatsapp_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
